language: python
python:
  - 3.7

stages:
  - build
  - lint
  - test
#  - name: deploy
#    if: branch = master

install: pipenv install --dev

jobs:
  include:
    - stage: build
      script: docker build -t taskie .

    - stage: lint
      script: flake8

    - stage: test
      script: pytest
      services: postgresql
      before_script:
        - psql -c "CREATE ROLE travis_ci_test WITH PASSWORD 'travis_ci_test';" -U postgres
        - psql -c 'CREATE DATABASE travis_ci_test OWNER travis_ci_test;' -U postgres
        - python manage.py migrate
      env:
        - DJANGO_SETTINGS_MODULE=taskie.settings.test

        - POSTGRES_NAME=travis_ci_test
        - POSTGRES_USER=travis_ci_test
        - POSTGRES_PASSWORD=travis_ci_test
        - POSTGRES_HOST=localhost
        - POSTGRES_PORT=5432
