language: python
python:
  - 3.7

stages:
  - build
  - lint
  - test
#  - name: deploy
#    if: branch = master

install: pipenv install --dev

jobs:
  include:
    - stage: build
      script: docker build -t taskie .

    - stage: lint
      script: flake8

    - stage: test
      script: pytest
      env:
        - DJANGO_SETTINGS_MODULE=taskie.settings.test

        - POSTGRES_NAME=taskie
        - POSTGRES_USER=taskie
        - POSTGRES_PASSWORD=taskie
        - POSTGRES_HOST=localhost
        - POSTGRES_PORT=5432
