language: python
python:
  - 3.7

stages:
  - build
  - lint
  - test
#  - name: deploy
#    if: branch = master

jobs:
  include:
    - stage: build
    - script: docker build -t taskie .

    - stage: lint
    - script: flake8

    - stage: test
    - script: pytest
